name: Build-x64dbg

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.9.9'
          host: 'windows'
          target: 'desktop'
          arch: win64_msvc2015_64
          dir: '${{ github.workspace }}/qt/'

      - name: Build
        run: |
          xmake.bat f --qt=${{env.Qt5_Dir}} -a x64
          xmake.bat

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: x64dbg
          path: build\windows\x64\release

