name: Build-x64dbg

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.9.9'
          host: 'windows'
          target: 'desktop'
          arch: win64_msvc2015_64
          dir: '${{ github.workspace }}/qt/'

      - name: Install Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Build
        run: |
          xmake f --qt=${{env.Qt5_Dir}} -a x64
          xmake

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: x64dbg
          path: build\windows\x64\release

